### ISSUE TITLE
PropType Errors Collapsed

### ISSUE THREAD

**Issue by craigjennings11** [davidgilbertson/react-recollect#122]
**Recollect version**
5.2.0

**Describe the bug**
PropType errors are collapsed under the "RENDER" output in the console, making them hard to find

![image](https://user-images.githubusercontent.com/1683368/79017131-3708de80-7b36-11ea-84b7-ba084e8cf022.png)

![image](https://user-images.githubusercontent.com/1683368/79017141-3a9c6580-7b36-11ea-98c9-9b4ef33c037e.png)

**Comment by davidgilbertson** [comment]
This is by design/necessary (but sucks, I know).

You want all console logs to fire in the correct order, or else they're of less use (I investigated deferring some errors, but that's asking for trouble).
And the collapsing is required, else the logs quickly become an unreadable wall of text (earlier versions didn't group the logs and it was painful).

As a general rule, leave debugging off unless you're looking into a particular issue.

I have added a line to the readme to explain that debugging will collapse all logs: https://github.com/davidgilbertson/react-recollect/commit/ed7a763cd1769fdef87ccffd526be3320fdc3f84
