### ISSUE TITLE
Can you please elaborate on how to convert `redux-saga` to use `react-recollect`?

### ISSUE THREAD

**Issue by gshilin** [davidgilbertson/react-recollect#125]

**Comment by davidgilbertson** [comment]
Have you read [Converting a Redux app to Recollect](https://medium.com/swlh/converting-a-redux-app-to-recollect-how-and-why-345a35088ea9?source=friends_link&sk=f7211c32ee398adce879661898948d2d)?

In addition to that, I'm not sure there's much _general_ guidance I can offer about `redux-saga` since all apps will be different. But at a high level:
* Use `async`/`await` or promises to handle async operations (nothing specific to Recollect). If you're unfamiliar, [MDN has some good info](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await).
* Wherever you are currently dispatching to the Redux store, you would replace that as described in the article about converting from Redux. In your sagas, I believe you'll mostly have `put` instead of `dispatch`.
* Generally speaking, Recollect doesn't require you to do anything in a particular way - you can write to the store object anywhere.

**Comment by davidgilbertson** [comment]
@gshilin I've closed this, let me know if there's anything else I can help with
