### ISSUE TITLE
Question: Would this work with Stencil?

### ISSUE THREAD

**Issue by danawoodman** [davidgilbertson/react-recollect#17]
This is sort of a random question, but would this work with the Stencil framework?

I've been playing with Stencil, which creates Web Components with a very similar API to React: 
https://stenciljs.com

I gave this a shot but it seems to fail on an import so I can't test this.

```
[ ERROR ]  Rollup: Missing Export: src/components/app-home/app-home.js:1:9
           'store' is not exported by
           node_modules/react-recollect/dist/index.js
```

Would be interesting to see if recollect could be made agnostic of React?

**Comment by davidgilbertson** [comment]
I wonder if this is a Rollup bug? Surely not as I'm building that dist/index.js file with the default Babel settings so the `Object.defineProperty(exports, "store", {` pattern is used in heaps of libraries.

There's a similar error, also related to stencil.js: https://github.com/typestack/class-transformer/issues/200.

I'll try a minimal build using Rollup.

**Comment by danawoodman** [comment]
Yeah it's weird. If you setup a brand new Stencil "app" project, install recollect and import it, you should be able to repro it. Thanks for investigating!

**Comment by danawoodman** [comment]
This relates to #44 right? Should we close this?

**Comment by davidgilbertson** [comment]
I'd leave this open, but I'm secretly hoping that the output of
Webpack-or-Rollup will be something Rollup understands.

**Comment by danawoodman** [comment]
Ok cool, let me know when you want me to checkout things 👍

**Comment by davidgilbertson** [comment]
I'm going to close this one now. Rollup no longer has a problem.

But for the question in the issue name, react-recollect isn't going to work with anything but React any time soon. The reason: internally it 'knows' which components are reading which properties from the store by tying in very closely with the lifecycle methods, and updates the store at a very specific point in time so that `shouldComponentUpdate` and `componentDidUpdate` get the previous/next versions of the store and allows React to do its PureComponent magic.

Maybe one day I'll go the Redux route of being UI agnostic, but for now I'll leave as is.

Thanks for your input!
