### ISSUE TITLE
TypeScript definitions are not in NPM release

### ISSUE THREAD

**Issue by stepanh** [davidgilbertson/react-recollect#37]
Hi David, nice idea for a lib & digging your writing style!

Having a go at setting it up with SSR+Typescript and met some resistance: 

1. `index.d.ts` is missing in the package published to NPM.
2. `store: object` causes errors in strict TS 
3. `PureComponent` is too specific
4. `collect` should return `ComponentType`

**How about this:**

recollect's `index.d.ts`:
```
declare module 'react-recollect' {
  import * as React from 'react';

  interface GlobalState {
  }
  
  interface WithStoreProp {
    store: GlobalState;
  }
  
  interface CollectorComponent extends React.Component {
    update(store: object): void,
    _name: string,
  }
  
  export function collect<P extends object>(Component: React.ComponentType<P>): React.ComponentType<P & WithStoreProp>;
  
  export const store: GlobalState;
  
  export function afterChange(callback: (
    newStore: GlobalState,
    propPath: string,
    updated: CollectorComponent[],
    oldStore: GlobalState
  ) => void): void;
}
```

User would define interface for _their global state_ in their project:
```

declare module 'react-recollect' {
  interface GlobalState {
    test?: string[];
    userName?: string; 
  }
}
```
Disclaimer: not fully tested

**Comment by davidgilbertson** [comment]
Thanks!

I actually don't know anything about TypeScript, I kinda hobbled that `index.d.ts` together and it seemed to work (I was just looking for the autocomplete, not to use in a TypeScript project).

If you've got a moment, would you mind testing what you've done? If you could do a PR that'd be great otherwise I'll just copy paste what you've got above :) and add something to the readme.

**Comment by stepanh** [comment]
Cool, I'll test and do a PR a bit later :-)

**Comment by davidgilbertson** [comment]
Thanks, much appreciated.
