### ISSUE TITLE
I'm probably doing something wrong

### ISSUE THREAD

**Issue by danawoodman** [davidgilbertson/react-recollect#55]
I've got a component, say `<BigFreakingList />` that has hundreds of items.

That then has a bunch of sub components, say `<SomeComplexComponent />`

Then finally I have `<ListItem />`

The only component I have wrapped in `collect()` is `<BigFreakingList />`.

I have a method called `Manager.update()`, which I pass down from `<SomeComplexComponent />` to `<ListItem />` which basically does:

```js
import { store } from 'react-recollect'

class Manager {
  async update () {
    store.items[id].loading = true
    await something()
    store.items[id].loading = false
  }
}
```

However, when `<ListItem />` is triggering `update` via clicking a button and I have `debugOn`, I get many hundreds of console log statements even though, I would assume I should just get a few related to updating the one `store.items[id]` item. 

Question is, what am I doing wrong? Should I wrap all components in `collect`?

~~My component does the loading update properly on the first pass, then just gets stuck:~~

EDIT: This is because I was assigning to a variable, making a change, then making another change rather than re-accessing the value from the store.

![](https://cl.ly/0760409d1f49/Screen%20Recording%202019-01-10%20at%2003.13%20PM.gif)

I'm getting pages upon pages of logs like this:

![](https://cl.ly/b432b9ce43d2/Screen%20Shot%202019-01-10%20at%203.06.21%20PM.png)

**Comment by danawoodman** [comment]
@davidgilbertson I'm sure you're a busy guy, but I'd love to figure out how to get things working well, attempting to add to a project :)

**Comment by davidgilbertson** [comment]
Sorry I've been slow replying, I'm knee deep in a new project.

In an original design I had it so that only one child component in an array of child components would update, but there's edge cases where that doesn't work, so the parent component will still go over all child components.

But when a component is defined as pure (with `PureComponent` or `React.memo`) the processing time is negligible.

Are your `<ListItem />` components defined as pure? If not, do that, and React shouldn't be trying to re-render the component (which will cause those `GET` messages).

Let me know how that goes.

**Comment by danawoodman** [comment]
Ok, so made all components in the tree `PureComponent` but I'm still getting a huge number of logs and slow rendering.

Is it normal to see so many log items with `__RR__.debugOn()`? Should I see a reduction in logs after making everything a PureComponent?

![](https://cl.ly/7b644bd1308e/Screen%20Shot%202019-01-20%20at%206.38.05%20PM.png)

Should

**Comment by davidgilbertson** [comment]
I'm not sure what exactly is going up here. I've made a codesandbox to demonstrate what should be happening. https://codesandbox.io/s/myy44z7j38

Here, the `<Product>` component has lots of instances, and when you click the favourite button, it updates the store. When it does that, the parent component `<Products>` will be re-rendered, but because `<Product>` is pure, only the child components that have changed will be re-rendered (as you can see with the single console log being fired).

A few things to note that might be causing your situation:
- When a parent component loops over some array to output all of the child components, it has to read something for each component, in this case just the ID:
```js
        {filteredProducts && filteredProducts.map(product => (
          <Product key={product.id} product={product}/>
        ))}
```

So in the console that shows up as:

![image](https://user-images.githubusercontent.com/4443482/51813760-1aef9780-230c-11e9-84ab-1e1c4eba4532.png)

This is fine, because all the reads are happening on the parent (at the speed of JavaScript, nothing is rendering at this point). Only one of these will actually trigger a render of the child, the one where the property changed.

Also worth noting is that the console logging itself is slow, unfortunately. You can see in that sandbox the difference on/off makes (if you didn't know, in codesandbox you have to select the sandbox in the dropdown to get the console that relates your code)

![image](https://user-images.githubusercontent.com/4443482/51813944-f8aa4980-230c-11e9-95b3-6d34c0eacde6.png)

Apologies for the slow reply!

**Comment by davidgilbertson** [comment]
I'm closing this now. FYI @danawoodman the logs to the console are now grouped (in v4.0.0), and I've added a note to the readme mentioning that this can effect performance.
