### ISSUE TITLE
View is not getting updated as expected when we update the store multiple keys in the store in the same function.

### ISSUE THREAD

**Issue by uidev547** [davidgilbertson/react-recollect#8]
View is not getting updated as expected, If i update the store multiple values in the same function.

In the given link https://codesandbox.io/s/jj9rjk2v65

In index.js line no: 17 and 18 updating the store,
But in the TaskList.jsx line no: 20 View is not getting updated as expected.

**Comment by uidev547** [comment]
> need to use the store passed to the component as props, rather than importing it.
Makes sense..

I tried with props store rather then importing it still I have the same problem,

https://codesandbox.io/s/m9pkk5wm8

**Comment by davidgilbertson** [comment]
Yes when _reading_ from the store in a component, use the store passed in as props.

When _writing_ to the store in some other place (like when fetching data from somewhere), use the store exported by `react-recollect`.

Your first example worked if you just changed the internals of the `<TaskList>` component. From this:
```jsx
import React from "react";
import { store, collect } from "react-recollect";
import Task from "./Task";

const TaskList = () => {
  return (
    <div>
      {!!store.tasks &&
        store.tasks.map(task => <Task key={task.id} task={task} />)}

      <button
        onClick={() => {
          store.tasks.push({
            id: Math.random(), // don't judge me
            name: "A new task",
            done: false
          });
        }}
      >
        Add a task {store.int} - {store.tasks[0].name}
      </button>
    </div>
  );
};
export default collect(TaskList);
```

to this (notice the store isn't being imported any more)

```js
import React from "react";
import { collect } from "react-recollect";
import Task from "./Task";

const TaskList = ({ store }) => {
  return (
    <div>
      {!!store.tasks &&
        store.tasks.map(task => <Task key={task.id} task={task} />)}

      <button
        onClick={() => {
          store.tasks.push({
            id: Math.random(), // don't judge me
            name: "A new task",
            done: false
          });
        }}
      >
        Add a task {store.int} - {store.tasks[0].name}
      </button>
    </div>
  );
};
export default collect(TaskList);
```

Example: https://codesandbox.io/s/10orq63854

And with your second example, since everything is inside the component with that example, you don't need to import the store at all, you can just use the one from props.
```jsx
import React, { Component } from "react";
import { collect } from "react-recollect";
import Task from "./Task";

class TaskList extends Component {
  componentDidMount() {
    let int = 0;
    setInterval(() => {
      int = int + 1;
      this.props.store.tasks[0].name = int;
      this.props.store.int = int;
    }, 3000);
  }
  render() {
    return (
      <div>
        {!!this.props.store.tasks &&
          this.props.store.tasks.map(task => (
            <Task key={task.id} task={task} />
          ))}

        <button
          onClick={() => {
            this.props.store.tasks.push({
              id: Math.random(), // don't judge me
              name: "A new task",
              done: false
            });
          }}
        >
          Add a task {this.props.store.int} - {this.props.store.tasks[0].name}
        </button>
      </div>
    );
  }
}
export default collect(TaskList);
```

I think I might need to try and do a nice warning in the console, it's not great how easy it is to do it wrong :(

**Comment by davidgilbertson** [comment]
OK having thought about it for a bit, I can explain why you were seeing this behaviour (and I'll add this to the readme).

You don't need to know all this (you just need to know to use the `props.store` inside components) but here it is anyway...

When React begins to re-render a component, if it's a `PureComponent` or `React.memo` component, it's going to compare the next version of the store with the previous version of the store. If they're the same, then it won't bother updating, which is great for performance.

To take advantage of this, Recollect holds two versions of the store at the point that a component is updated. There's the `store` that was passed in as props, and the global `store` that you can import from `react-recollect`.

At the exact moment of a render, they _need_ to be different so that React can compare the two for performance gains.

So, when you were referring to the global `store` object in the `render()` method of your component, it was the 'previous' version of the store. Hence one step behind.

Hope that helps.

**Comment by uidev547** [comment]
> Yes when reading from the store in a component, use the store passed in as props.
When writing to the store in some other place (like when fetching data from somewhere), use the store exported by react-recollect.

These statements will explain the solution to the problem.

Thankyou for deep explanation..
