### ISSUE TITLE
Outdated stores silently reject updates

### ISSUE THREAD

**Issue by Kycermann** [davidgilbertson/react-recollect#92]
Before the following section of code is ran, elements are updated and re-rendered. My understanding is that with each new render cycle, the store passed in props in the previous cycle becomes outdated and it seems to silently reject updates.

```
function setTab(store, index) {
    // ... logic that causes updates and renders, checked using __RR__.debugOn()

    console.log("Current tab index: ", store.currentTabIndex); // 1
    console.log("New tab index: ", store.currentTabIndex - 1); // 0

    store.currentTabIndex--; // silently rejected

    console.log("Stores are equal: ", window.__RR__.internals.store === store); // false, should be true

    console.log("Current tab index: ", store.currentTabIndex); // 1, should be 0
}
```

This took me a while to figure out but I solved it by changing my function from `setTab(store, index)` to `setTab(index)` and using `import {store} from "react-recollect"`.

I found this tricky to debug, a warning or exception would have made things easier. How comes old instances of the store, such as in the above example, can't be written to?

**Comment by davidgilbertson** [comment]
What version are you using? From 5 onwards, it shouldn't matter which store you read from.

This code should work. It's quite similar to this test: https://github.com/davidgilbertson/react-recollect/blob/master/tests/integration/readFromTwoStores.test.tsx#L17-L20

Doing `window.__RR__.internals.store === store` will probably be confusing when troubleshooting, since you're check if they're the same object. 
What you want to do is `window.__RR__.internals.store.currentTabIndex === store.currentTabIndex` or maybe `JSON.stringify(window.__RR__.internals.store) === JSON.stringify(store)`

Internally, reads/writes are redirected so it doesn't matter if they're the same object or not (I will clarify this in the readme). For the record, the `store` you import and `window.__RR__.internals.store` are the same object, while the `store` passed to React is different on each render, (for React's sake).

**Comment by Kycermann** [comment]
I haven't been able to reproduce this in version 5. Thank you for the information.
